# Generated by Django 5.2.8 on 2025-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmedia_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='media',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
