# Generated by Django 5.2.8 on 2025-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsmedia_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmedia',
            name='media',
            field=models.FileField(upload_to='news/'),
        ),
    ]
