# Generated by Django 5.2.8 on 2025-11-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_by', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
                ('file', models.FileField(upload_to='proposals/files/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
