# Generated by Django 5.2.8 on 2025-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propolsals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='file',
            field=models.FileField(upload_to='proposals/'),
        ),
    ]
