# Generated by Django 5.2.8 on 2025-11-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propolsals', '0002_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='type',
            field=models.CharField(choices=[('product-enchancement', 'Product Enchancement'), ('process-optimization', 'Process Optimization'), ('user-experience', 'User Experience'), ('cost-reduction', 'Cost Reduction'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
