# Generated by Django 5.2.8 on 2025-11-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propolsals', '0002_alter_proposal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='type',
            field=models.CharField(choices=[('product-enchancement', 'Product Enchancement'), ('process-optimization', 'Process Optimization'), ('user-experience', 'User Experience'), ('cost-reduction', 'Cost Reduction'), ('other', 'Other')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
