# Generated by Django 5.2.8 on 2025-11-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propolsals', '0003_alter_proposal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('pilot', 'Pilot')], default='pending', max_length=255),
        ),
    ]
