# Generated by Django 5.2.8 on 2025-11-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propolsals', '0003_proposal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='type',
            field=models.CharField(blank=True, choices=[('product-enchancement', 'Product Enchancement'), ('process-optimization', 'Process Optimization'), ('user-experience', 'User Experience'), ('cost-reduction', 'Cost Reduction'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
